[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "14.15.0"
  
[[headers]]
  X-Frame-Options= "SAMEORIGIN"

[[plugins]]
  package = "@netlify/plugin-gatsby"

  
[[redirects]]
  from = "https://nikitajain.in/portfolio"
  to = "https://www.playbook.com/s/nikita-jain/portfolio"
  status = 301
  force = true
  
[[redirects]]
  from = "https://nikitajain.in/resume"
  to = "https://drive.google.com/file/d/1wcev8kJhPwRwtcf9zOXDhDlSUxzhqdmW/view?usp=drive_link"
  status = 301
  force = true
