---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
- type: document
  path: src/content/pages/index.md
  label: Home
  templates:
  - home
- type: document
  path: src/content/pages/contact.md
  label: Contact
  templates:
  - contact
- type: directory
  path: src/content/pages
  label: Pages
  create: all
  match: "*"
  exclude: "{index.md,contact.md}"
  templates:
  - page
- type: directory
  path: src/content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
